export const ReportsMainData = [
  {
    arabic: "الموظفون",
    english: "Employees",
    link: "/main/employeesreport",
    icon: "fa-solid fa-address-book",
  },
  {
    arabic: "أوقات العمل",
    english: "Working Time ",
    link: "/main/workingtimereport",
    icon: "fa-solid fa-calendar-days",
  },
  {
    arabic: "حالة اليوم",
    english: "Day Status",
    link: "/main/dayreports",
    icon: "fa-solid fa-circle-question",
  },
  {
    arabic: "حضور تفصيلي",
    english: "Detailed Attendance",
    link: "/main/attendreport",
    icon: "fa-solid fa-magnifying-glass-plus",
  },
  {
    arabic: "إجمالي الحضور",
    english: "Total Attendance",
    link: "/main/totalattendreport",
    icon: "fa-solid fa-chart-line",
  },
  {
    arabic: "الغياب",
    english: "Absence",
    link: "/main/absencereport",
    icon: "fa-solid fa-user-minus",
  },
  {
    arabic: "تأخير",
    english: "Delay",
    link: "/main/delayreport",
    icon: "fa-solid fa-hourglass-start",
  },
  {
    arabic: "حركات غير مكتملة",
    english: "Incompleted trans",
    link: "/main/incolpletedreport",
    icon: "fa-solid fa-puzzle-piece",
  },
  {
    arabic: "حضور المبكر",
    english: "Early Attendance",
    link: "/main/earlyattendancereport",
    icon: "fa-solid fa-hand",
  },
  {
    arabic: "ملخص الحضور",
    english: "Attendance Summary",
    link: "/main/attendancesummaryreport",
    icon: "fa-solid fa-chart-area",
  },
  {
    arabic: "ملخص الحضور الكلي",
    english: "Total Attendance Summary",
    link: "/main/totalattendancesummaryreport",
    icon: "fa-solid fa-list",
  },
  {
    arabic: "الاضافي",
    english: "Overtime",
    link: "/main/overtimereport",
    icon: "fa-solid fa-business-time",
  },
  {
    arabic: "دوام الموظفين تفصيلي",
    english: "Working Time Details",
    link: "/main/shiftdetailsreport",
    icon: "fa-solid fa-sheet-plastic",
  },
  {
    arabic: "الحضور والانصراف بالفروع",
    english: "Branch Attendance",
    link: "/main/attendecebranchreport",
    icon: "fa-solid fa-building",
  },
  {
    arabic: "اجازات الموظفين",
    english: "Vacations",
    link: "/main/vacationsreports",
    icon: "fa-solid fa-circle-stop",
  },
  {
    arabic: "اذونات الموظفين",
    english: "Permissions Report",
    link: "/main/permissionsreports",
    icon: "fa-solid fa-person-walking",
  },
  {
    arabic: "التاخير والانصراف المبكر",
    english: "Delay and Early Leave",
    link: "/main/delayearlyleavereport",
    icon: "fa-solid fa-bed",
  },
  {
    arabic: "اجمالي الغياب",
    english: "Total Absence",
    link: "/main/totalabence",
    icon: "fa-solid fa-ban",
  },
  {
    arabic: "اجمالي التأخير",
    english: "Total Delay",
    link: "/main/totaldelay",
    icon: "fa-solid fa-clock-rotate-left",
  },
];
