export const employeesReportTempData = [
  {
    id: 1,
    name: "abdullah",
    branch: "branch 1",
    mangement: "Mangement 1",
    department: "Department 1",
    shift: "workingTime 1",
    job: "job 1",
    groub: "group 1",
  },
  {
    id: 2,
    name: "ahmed",
    branch: "branch 2",
    mangement: "Mangement 2",
    department: "Department 2",
    shift: "workingTime 2",
    job: "job 2",
    groub: "group 2",
  },
  {
    id: 3,
    name: "abdu",
    branch: "branch 3",
    mangement: "Mangement 3",
    department: "Department 3",
    shift: "workingTime 3",
    job: "job 3",
    groub: "group 3",
  },
];
