export const permissionTempData = [
  {
    code: 1,
    name: "abdullah",
    date: "2023-07-10",
    branch: "branch 1",
    workingTime: "Shift 1",
    type: "مؤقت",
    typeVal :'Temporary',
    shift: "first",
    in: "10:00",
    out: "12:30",
  },
  {
    code: 2,
    name: "abdu",
    date: "2023-07-13",
    branch: "branch 2",
    workingTime: "Shift 2",
    type: "حضور متاخر",
    typeVal :'Late',
    shift: "first",
    in: "11:00",
    out: "12:30",
  },
  {
    code: 3,
    name: "ahmed",
    date: "2023-08-10",
    branch: "branch 3",
    workingTime: "Shift 3",
    type: "انصراف مبكر",
    typeVal :'Early',
    shift: "first",
    in: "09:00",
    out: "12:30",
  },
  {
    code: 4,
    name: "abdullah",
    date: "2023-07-09",
    branch: "branch 4",
    workingTime: "Shift 4",
    type: "يوم كامل",
    typeVal :'AllDay',
    shift: "first 4",
    in: "10:00",
    out: "12:00",
  },
];
