export const tempEmployeesData = [
  {
    id: 1,
    nameAr: "أحمد",
    nameEn: "ahmed",
    branch: "branch 1",
    mangement: "Management 1",
    department: "Department 1",
    shift: "Shift 1",
    active: true,
  },
  {
    id: 2,
    nameAr: "عبده",
    nameEn: "ab",
    branch: "branch 2",
    mangement: "Management 2",
    department: "Department 2",
    shift: "Shift 2",
    active: true,
  },
  {
    id: 3,
    nameAr: "احمد",
    nameEn: "ahmed",
    branch: "branch 3",
    mangement: "Management 3",
    department: "Department 3",
    shift: "Shift 3",
    active: true,
  },
  {
    id: 4,
    nameAr: "عبدالله",
    nameEn: "abdullah",
    branch: "branch 4",
    mangement: "Management 4",
    department: "Department 4",
    shift: "Shift 4",
    active: true,
  },
  {
    id: 5,
    nameAr: "احمد",
    nameEn: "ahmed",
    branch: "branch 5",
    mangement: "Management 5",
    department: "Department 5",
    shift: "Shift 5",
    active: true,
  },
];
