export const tempEmployeesData = [
  {
    id: 1,
    nameAr: "أحمد",
    nameEn: "ahmed",
    branch: "branch 1",
    mangement: "Mangement 1",
    department: "Department 1",
    shift: "workingTime 1",
    active: true,
  },
  {
    id: 2,
    nameAr: "عبده",
    nameEn: "ab",
    branch: "branch 2",
    mangement: "Mangement 2",
    department: "Department 2",
    shift: "workingTime 2",
    active: true,
  },
  {
    id: 3,
    nameAr: "احمد",
    nameEn: "ahmed",
    branch: "branch 3",
    mangement: "Mangement 3",
    department: "Department 3",
    shift: "workingTime 3",
    active: true,
  },
  {
    id: 4,
    nameAr: "عبدالله",
    nameEn: "abdullah",
    branch: "branch 4",
    mangement: "Mangement 4",
    department: "Department 4",
    shift: "workingTime 4",
    active: true,
  },
];
