export const late = [{
    code :'11',
    name :'22',
    branch :'33',
    shift :'44',
    late :'55',
    date :'66',
},{
    code :'11',
    name :'22',
    branch :'33',
    shift :'44',
    late :'55',
    date :'66',
},{
    code :'11',
    name :'22',
    branch :'33',
    shift :'44',
    late :'55',
    date :'66',
},{
    code :'11',
    name :'22',
    branch :'33',
    shift :'44',
    late :'55',
    date :'66',
    },]

    export const absentData = [{
        code :'11',
        name :'22',
        branch :'33',
        shift :'44',
        late :'55',
        date :'66',
    },{
        code :'11',
        name :'22',
        branch :'33',
        shift :'44',
        late :'55',
        date :'66',
    },{
        code :'11',
        name :'22',
        branch :'33',
        shift :'44',
        late :'55',
        date :'66',
    },{
        code :'11',
        name :'22',
        branch :'33',
        shift :'44',
        late :'55',
        date :'66',
        },
        {
            code :'11',
            name :'22',
            branch :'33',
            shift :'44',
            late :'55',
            date :'66',
        },{
            code :'11',
            name :'22',
            branch :'33',
            shift :'44',
            late :'55',
            date :'66',
        },
        {
            code :'11',
            name :'22',
            branch :'33',
            shift :'44',
            late :'55',
            date :'66',
        },{
            code :'11',
            name :'22',
            branch :'33',
            shift :'44',
            late :'55',
            date :'66',
        },]

    