export const tempJopsData = [
  { nameAr: "وظيفة 1", nameEn: "job 1" },
  { nameAr: "وظيفة 2", nameEn: "job 2" },
  { nameAr: "وظيفة 3", nameEn: "job 3" },
  { nameAr: "وظيفة 4", nameEn: "job 4" },
  { nameAr: " وظيفة 5", nameEn: "job 5" },
  { nameAr: "وظيفة 6", nameEn: "job 6" },
  { nameAr: "وظيفة 7", nameEn: "job 7" },
  { nameAr: "وظيفة 8", nameEn: "job 8" },
  { nameAr: "وظيفة 9", nameEn: "job 9" },
  { nameAr: "وظيفة 10", nameEn: "job 10" },
  { nameAr: "وظيفة 11", nameEn: "job 11" },
  { nameAr: "وظيفة 12", nameEn: "job 12" },
  { nameAr: "وظيفة 13", nameEn: "job 13" },
  { nameAr: "وظيفة 14", nameEn: "job 14" },
  { nameAr: "وظيفة 15", nameEn: "job 15" },
];
